default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: evan
  password: ENV['DB_PASSWORD']

development:
  <<: *default
  database: evan

test:
  <<: *default
  database: evan

production:
  <<: *default
  database: noexist
  username: noexist
